### ISSUE TITLE
CryptoDredge 0.15.0 binary filename mismatch

### ISSUE THREAD

**Issue by LuKePicci** [papampi/nvOC_miners#31]
The CryptoDredge 0.15.0 tarball for the 3.0-miners branch contains a binary which is not named in a valid way to get it working in the 3.0 branch. The package for 3.1-miners is fine since the binary filename is correctly specified in its version specific json pm manifest.

**Comment by papampi** [comment]
Updated to 0.16.1 
https://github.com/papampi/nvOC_miners/commit/e11afea28ad1a5f649b59ee43f6fc040d53fcb32
https://github.com/papampi/nvOC_miners/commit/704157de328aabe510d885ca7092bc5dc465b261
