### ISSUE TITLE
Miner not restart during miner upgrade

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_miners#35]
stop_if_needed and restart_if_needed not working with pluggable miners

**Comment by papampi** [comment]
Was mining with Phoenix and run upgrade:

```
Extracting Phoenix 12.0 for 9.2
PhoenixMiner_4.1c_Linux/start_miner.sh
PhoenixMiner_4.1c_Linux/epools.txt
PhoenixMiner_4.1c_Linux/Readme.txt
PhoenixMiner_4.1c_Linux/dpools.txt
PhoenixMiner_4.1c_Linux/PhoenixMiner
PhoenixMiner_4.1c_Linux/ReleaseNotes.txt
PhoenixMiner_4.1c_Linux/config.txt
 -> Phoenix for 9.2 updated

```

No stop and restart

**Comment by LuKePicci** [comment]
If I remember correctly, restart should occur only when running miner binary needs to get replaced. If you delete running version manifest and force it to reinstall ou should see the stop/start.

Da: Payam Nab
Inviato: venerdì 8 marzo 2019 18:02
A: papampi/nvOC_miners
Cc: Luca Piccirillo; Assign
Oggetto: Re: [papampi/nvOC_miners] Miner not restart during miner upgrade(#35)

Was mining with Phoenix and run upgrade:
Extracting Phoenix 12.0 for 9.2
PhoenixMiner_4.1c_Linux/start_miner.sh
PhoenixMiner_4.1c_Linux/epools.txt
PhoenixMiner_4.1c_Linux/Readme.txt
PhoenixMiner_4.1c_Linux/dpools.txt
PhoenixMiner_4.1c_Linux/PhoenixMiner
PhoenixMiner_4.1c_Linux/ReleaseNotes.txt
PhoenixMiner_4.1c_Linux/config.txt
 -> Phoenix for 9.2 updated

No stop and restart

**Comment by papampi** [comment]
That's what I did, removed manifest and forced it to reinstall the miner, got no stop/restart

**Comment by LuKePicci** [comment]
Please run `ps ax` and post here the results, I need to see what the running miner command line looks like.

**Comment by papampi** [comment]
Here you go ...  


```
31687 ?        Ss     0:00 SCREEN -c /home/m1/NVOC/testing/screenrc-miner -dmSL miner /home/m1/NVOC/testing/miners/PhoenixMiner/recommended/PhoenixMiner -pool stratum+tcp://eu1.ethermine.org:4444 -wal WALETT_ADDRESS -worker nv105 -pass x -coin eth -wdog 1 -rmode 0 -nvidia -proto 3 -cdmport 192.168.1.105:3333 -retrydelay 5 -gpus 1,2,3,4,5,6,7,8,9,10,11,12
31690 pts/23   Ssl+   2:32 /home/m1/NVOC/testing/miners/PhoenixMiner/recommended/PhoenixMiner -pool stratum+tcp://eu1.ethermine.org:4444 -wal WALETT_ADDRESS -worker nv105 -pass x -coin eth -wdog 1 -rmode 0 -nvidia -proto 3 -cdmport 192.168.1.105:3333 -retrydelay 5 -gpus 1,2,3,4,5,6,7,8,9,10,11,12
```

**Comment by LuKePicci** [comment]
Alright, I see the issue. Will search for a solution asap.

**Comment by papampi** [comment]
It's because of recommended/latest path?

**Comment by papampi** [comment]
I think we should restart miner if either is used, usually updating miner, updates both symlinks.

**Comment by LuKePicci** [comment]
Just committed a patch for this, please verify it is working fine https://github.com/papampi/nvOC_miners/commit/a0e66605b84596a0177cc5804499219e1e5da607

**Comment by papampi** [comment]
Nope, no restart.

```
Extracting PhoenixMiner 4.1c for 9.2
PhoenixMiner_4.1c_Linux/start_miner.sh
PhoenixMiner_4.1c_Linux/epools.txt
PhoenixMiner_4.1c_Linux/Readme.txt
PhoenixMiner_4.1c_Linux/dpools.txt
PhoenixMiner_4.1c_Linux/PhoenixMiner
PhoenixMiner_4.1c_Linux/ReleaseNotes.txt
PhoenixMiner_4.1c_Linux/config.txt
 -> PhoenixMiner for 9.2 updated
```

**Comment by LuKePicci** [comment]
Please, check if it works when using exact version instead of "recommended" in 1bash.

**Comment by papampi** [comment]
Yup, works as it should

```
Extracting PhoenixMiner 4.1c for 9.2
PhoenixMiner_4.1c_Linux/start_miner.sh
PhoenixMiner_4.1c_Linux/epools.txt
PhoenixMiner_4.1c_Linux/Readme.txt
PhoenixMiner_4.1c_Linux/dpools.txt
PhoenixMiner_4.1c_Linux/PhoenixMiner
PhoenixMiner_4.1c_Linux/ReleaseNotes.txt
PhoenixMiner_4.1c_Linux/config.txt
Stopping miner
screen killed (pid 7852)
bash killed (pid 7856)
screen killed (pid 7756)
screen killed (pid 7906)
Restarting nvOC...
bash killed (pid 7701)
 -> PhoenixMiner for 9.2 updated
```

**Comment by LuKePicci** [comment]
Retry now, if this still doesn't work print the value of $1 into stop-if-needed function

Da: Payam Nab
Inviato: venerdì 8 marzo 2019 21:35
A: papampi/nvOC_miners
Cc: Luca Piccirillo; Assign
Oggetto: Re: [papampi/nvOC_miners] Miner not restart during miner upgrade(#35)

Yup, works as it should
Extracting PhoenixMiner 4.1c for 9.2
PhoenixMiner_4.1c_Linux/start_miner.sh
PhoenixMiner_4.1c_Linux/epools.txt
PhoenixMiner_4.1c_Linux/Readme.txt
PhoenixMiner_4.1c_Linux/dpools.txt
PhoenixMiner_4.1c_Linux/PhoenixMiner
PhoenixMiner_4.1c_Linux/ReleaseNotes.txt
PhoenixMiner_4.1c_Linux/config.txt
Stopping miner
screen killed (pid 7852)
bash killed (pid 7856)
screen killed (pid 7756)
screen killed (pid 7906)
Restarting nvOC...
bash killed (pid 7701)
 -> PhoenixMiner for 9.2 updated

**Comment by papampi** [comment]
Fixed, thanks.
