### ISSUE TITLE
restart or start nvoc starts from mining folder not from testing one

### ISSUE THREAD

**Issue by psynauty** [papampi/nvOC_miners#37]

**Comment by LuKePicci** [comment]
This is not a miners issue, should be moved in the main repo. Did you run `bash nvOC start/restart` from inside the testing folder?

**Comment by psynauty** [comment]
Sorry. Since I encountered this after cloning the miner profile to a testing one, I assumed that guake would invoke everything via the testing folder.
Terminal seems to be starting in the testing folder as per the profile modification.
So not sure why guake defaults to the miner one.
I leave it up to you as to where this should reside, if an issue at all.

**Comment by LuKePicci** [comment]
It all depends on the guake current directory while you run nvOC start/restart scripts. I don't remember which is the guake current directory on launch, but the nvOC script inside testing starts/restarts the testing, that one inside mining does it on mining. Do some experiments on this and close this issue if you find is all working as expected.
