### ISSUE TITLE
Claymore and Ethminer need post-fork updates

### ISSUE THREAD

**Issue by loumposa** [papampi/nvOC_miners#39]
I've downloaded the new Claymore 14.7
The file was extracted under Claymore folder and the folder was named in 1bash as 14.7
The miners will not start
![Claymore Path 14 7](https://user-images.githubusercontent.com/35316261/60081934-bd307180-972a-11e9-83f9-bce84b40b695.jpeg)
![Error Miner Not Started](https://user-images.githubusercontent.com/35316261/60081935-bdc90800-972a-11e9-9169-7c14c48e273c.jpeg)
![1bash Claymore Setup](https://user-images.githubusercontent.com/35316261/60081936-bdc90800-972a-11e9-8548-8944b86b479a.jpeg)

**Comment by papampi** [comment]
When manually update miner, you should copy miner manifest (nvoc-miner.json) from older version and edit both new one and the old one.
I just updated claymore to latest.

**Comment by LuKePicci** [comment]
@loumposa Editing the manifest of the old miner version is only needed if you have defined also an install section in the new one (see what @papampi did for old 12.0 version here: https://github.com/papampi/nvOC_miners/commit/aafb3af9a29718ee08ba6c3a76336e42b77e90b8)

For example, this minimal manifest would have been totally fine for a manual quick update of claymore:
```
{
	"friendlyname": "Claymore",
	"version": "14.7",
	"hcd": "ethdcrminer64 -epool ${!xpool}:${!xport} -ewal ${!xaddr}${!xwallet}${!xwork} -epsw $MINER_PWD -mode 1 -dbg -1 ",
	"devlist_argument": "-di ",
	"devlist_separator": "",
	"devlist_format": "A",

	"foreman": {
		"name": "claymore-eth",
		"api_ext": "-mport -3333"
	},

	"minerinfo": {
		"total_hash": "tail -100 ${NVOC}/nvoc_logs/screenlog.0 | grep \"Total Speed:\" | grep -v grep |sed -r 's/\\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' | awk '{print $5}' | awk '{s+=$1} END {printf \"%.0f\", s}' ,
		"hash_count": "tail -100 ${NVOC}/nvoc_logs/screenlog.0 | grep \"Total Speed:\" | grep -v grep | wc -l | awk '{print $1}'",
		"solution_speed_unit": "Mh/s",
		"miner_error": "tail -n 100 ${NVOC}/nvoc_logs/screenlog.0 |  grep \"No new jobs\" | tail -n $TAIL_GPU_COUNT |  sed -r 's/\\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' | awk '{print $0,\"<br>\"}'",
		"rejected_shares": "tail -100 ${NVOC}/nvoc_logs/screenlog.0 | grep -o \"Rejected: [0-9]*\" | tail -1 | awk '{print $2}"
	},
}
```

and both minerinfo and foreman sections are optional too if you are unsure about how to configure them.

**Pro tip:** if you create your own miner package for early updates or new miners testing I suggest you give customized miner version names like `14.7-my` to avoid potential conflicts when that miner version gets included officially in this repo.

**Comment by LuKePicci** [comment]
claymore was updated already to support post-fork changes, we'll track ethminer progresses in #41
