### ISSUE TITLE
Update ethminer to 0.18.0

### ISSUE THREAD

**Issue by shanesnofear** [papampi/nvOC_miners#41]
there's a updated/alpha 0.19.0 version of ethminer that dropped

thanks for whoever updates it !!

**Comment by LuKePicci** [comment]
alpha is not worth now, I think we should go for the stable 0.18.0 released 5 days ago instead

**Comment by shanesnofear** [comment]
your probably right I did not even notice that there was a new stable also the 0.19.0 alpha was not submitting shares on windows when I was testing it

**Comment by LuKePicci** [comment]
Let's keep this open as reminder for 0.18.0 to be updated

**Comment by LuKePicci** [comment]
@papampi I'm out for holidays, and I would like to avoid testing things remotely. Could you take care of updating ethminer?
