### ISSUE TITLE
PM tarball_subpath depth stuck at 0

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_miners#43]
@LuKePicci 
Can you please check this, it wont get updated.
https://github.com/papampi/nvOC_miners/blob/3.2-miners/CryptoDredge/0.22.0/.nvoc-miner.json
Tried with:
`"tarball_subpath": "CryptoDredge_0.22.0",
Still get error

`

**Comment by LuKePicci** [comment]
Great to hear from you again.
CryptoDredge 0.22.0 tarball contains a single folder with binary contents we need, so we want to extract it using `--strip 1`

The `tarball_subpath` works like this:
- if no `tarball_subpath` is defined in manifest (like it was previously to its introduction) the old behavior is retained, tar gets extracted with `--strip 1` argument, so if you entirely remove `tarball_subpath` it will work, please note `tarball_subpath=""` is not the same as if you remove it
- in any other case, we count the slashes in `tarball_subpath`, say N the number of slashes, and we do `--strip N`, so you can gat it working by using `tarball_subpath="CryptoDredge_0.22.0/"`

Done in https://github.com/papampi/nvOC_miners/commit/946ec9a8ae6260e957e1488c27368be9dea4e879, let me know

**Comment by papampi** [comment]
Thanks mate,  
But still giving error 
```
Downloading CryptoDredge_0.22.0_cuda_9.2_linux.tar.gz
/home/m1/NVOC/m 100%[=======>]  20.91M  1.57MB/s    in 25s
Extracting CryptoDredge 0.22.0
CryptoDredge_0.22.0/
CryptoDredge_0.22.0/run-x16rv2-bsod.sh
CryptoDredge_0.22.0/README.txt
CryptoDredge_0.22.0/LICENSE.txt
CryptoDredge_0.22.0/RELEASE-NOTES.txt
CryptoDredge_0.22.0/CryptoDredge
CryptoDredge_0.22.0/config.json
chmod: cannot access '/home/m1/NVOC/mining/miners/CryptoDredge/0.22.0/CryptoDredge': No such file or directory
 -> CryptoDredge update failed
```

And
```
m1@m1-desktop:~$ ll NVOC/mining/miners/CryptoDredge/0.22.0/
total 21428
drwxrwxr-x 3 m1 m1     4096 Dec  2 23:49 ./
drwxrwxr-x 6 m1 m1     4096 Dec  2 19:54 ../
drwxr-xr-x 2 m1 m1     4096 Oct  2 06:12 CryptoDredge_0.22.0/
-rw-rw-r-- 1 m1 m1 21924547 Oct  2 09:28 CryptoDredge_0.22.0_cuda_9.2_linux.tar.gz
-rw-rw-r-- 1 m1 m1     1471 Dec  2 23:49 .nvoc-miner.json
```

**Comment by LuKePicci** [comment]
Got it, there was a bug with a variable name. I confirm the trailing "/" is needed in subpaths like `CryptoDredge/`

**Comment by papampi** [comment]
@LuKePicci 
Kudos to tarball_url idea, its amazing.

**Comment by LuKePicci** [comment]
Yeah, the ro idea is old but the real challenge was to make tar command o eztract only what we needed into some specific location

--------------

Da: Payam Nab
Inviato: martedì 3 dicembre 2019 09:07
A: papampi/nvOC_miners
Cc: Luca Piccirillo; Mention
Oggetto: Re: [papampi/nvOC_miners] PM tarball_subpath depth stuck at 0 (#43)

@LuKePicci
Kudos to tarball_url idea, its amazing.
