### ISSUE TITLE
nvOC update script: typo for stopping watchdog

### ISSUE THREAD

**Issue by Alysko** [papampi/nvOC_miners#5]
Hi,
line 4, `pkill -f 5watcdog` should be pkill -f 5watc**h**dog

**Comment by LuKePicci** [comment]
I'm pretty confident that stopping miner while installing updates may not be necessary.

**Comment by papampi** [comment]
@LuKePicci 
Dont you think when miner is running untar can not overwrite the running miner and gets "file busy error"?

**Comment by LuKePicci** [comment]
If nobody else or the miner itself opened that binary file it should not. Ethminer for sure doesn't.

**Comment by papampi** [comment]
Miner is running and is using it so the file should be busy and can not be over written.
I'm sure many times when I try to copy new miners, it gave me file busy error, may be tar is different from copy.

**Comment by papampi** [comment]
Dont remember, Claymore or DSTM

**Comment by LuKePicci** [comment]
Try to overwrite them when running, if they gives you the error we can kill them before overwriting with the updated version. so the running miner does not get killed if it is not getting updated or does not keep an open handle on the binary executable.

**Comment by papampi** [comment]
#8

**Comment by Alysko** [comment]
Be carefull, I already had problem updating miners while mining. Justly sort of "file busy error".

**Comment by papampi** [comment]
That is taken care of in PR #8 
If a miner has update and is running it will stop only for a second to copy new one and start again.
No time is wasted...

**Comment by Alysko** [comment]
Be carefull, I already had problem updating miners while mining. Justly sort of "file busy error".

**Comment by papampi** [comment]
You mean you tested PR #8 and it gives you error?

**Comment by LuKePicci** [comment]
Fixed
